default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

development:
  <<: *default
  database: Greetings_development

test:
  <<: *default
  database: Greetings_test

production:
  <<: *default
  database: Greetings_production
  username: Greetings
  password: <%= ENV["GREETINGS_DATABASE_PASSWORD"] %>