Greeting.create(message: "Hello!")
Greeting.create(message: "How are you?")
Greeting.create(message: "Happy New Year!")
Greeting.create(message: "Marry Christmas!")
Greeting.create(message: "I am fine, thank you.")
Greeting.create(message: "Welcome to this website.")